/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.3.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class AccountsApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  addAccount(addAccountRequest) {
    // verify the required parameter 'addAccountRequest' is set
    if (addAccountRequest === undefined || addAccountRequest === null) {
      throw new Error(
        "Missing the required parameter 'addAccountRequest' when calling addAccount",
      );
    }

    let path = "/accounts";

    let options = {
      params: {},
      data: addAccountRequest,
    };

    return this.accounting.request("POST", path, options);
  }

  deleteAccount(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling deleteAccount",
      );
    }

    let path = "/accounts/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("DELETE", path, options);
  }

  getAccount(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling getAccount",
      );
    }

    let path = "/accounts/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listAccounts(fields = null, page = null, perPage = null) {
    let path = "/accounts";

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  updateAccount(uuid, addAccountRequest) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling updateAccount",
      );
    }

    // verify the required parameter 'addAccountRequest' is set
    if (addAccountRequest === undefined || addAccountRequest === null) {
      throw new Error(
        "Missing the required parameter 'addAccountRequest' when calling updateAccount",
      );
    }

    let path = "/accounts/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: addAccountRequest,
    };

    return this.accounting.request("PUT", path, options);
  }
}
