/**
 * Accounting API
 *
 * The version of the OpenAPI document: 7.5.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class AttachmentsApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  addAttachment(addAttachmentRequest) {
    // verify the required parameter 'addAttachmentRequest' is set
    if (addAttachmentRequest === undefined || addAttachmentRequest === null) {
      throw new Error(
        "Missing the required parameter 'addAttachmentRequest' when calling addAttachment",
      );
    }

    let path = "/attachments";

    let options = {
      params: {},
      data: addAttachmentRequest,
    };

    return this.accounting.request("POST", path, options);
  }

  deleteAttachment(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling deleteAttachment",
      );
    }

    let path = "/attachments/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("DELETE", path, options);
  }

  getAttachment(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling getAttachment",
      );
    }

    let path = "/attachments/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listAttachments(fields = null, page = null, perPage = null) {
    let path = "/attachments";

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  retrieveAttachments(resource, fields = null, page = null, perPage = null) {
    // verify the required parameter 'resource' is set
    if (resource === undefined || resource === null) {
      throw new Error(
        "Missing the required parameter 'resource' when calling retrieveAttachments",
      );
    }

    let path = "/attachments/resource/{resource}";
    path = path.replace("{resource}", resource);

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  updateAttachment(uuid, addAttachmentRequest) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling updateAttachment",
      );
    }

    // verify the required parameter 'addAttachmentRequest' is set
    if (addAttachmentRequest === undefined || addAttachmentRequest === null) {
      throw new Error(
        "Missing the required parameter 'addAttachmentRequest' when calling updateAttachment",
      );
    }

    let path = "/attachments/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: addAttachmentRequest,
    };

    return this.accounting.request("PUT", path, options);
  }
}
