/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.0.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class AuthApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  authInit() {
    let path = "/auth/init";

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  login(loginRequest) {
    // verify the required parameter 'loginRequest' is set
    if (loginRequest === undefined || loginRequest === null) {
      throw new Error(
        "Missing the required parameter 'loginRequest' when calling login",
      );
    }

    let path = "/auth/login";

    let options = {
      params: {},
      data: loginRequest,
    };

    return this.accounting.request("POST", path, options);
  }

  logout() {
    let path = "/auth/logout";

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  switchCompany(switchCompanyRequest) {
    // verify the required parameter 'switchCompanyRequest' is set
    if (switchCompanyRequest === undefined || switchCompanyRequest === null) {
      throw new Error(
        "Missing the required parameter 'switchCompanyRequest' when calling switchCompany",
      );
    }

    let path = "/auth/switch";

    let options = {
      params: {},
      data: switchCompanyRequest,
    };

    return this.accounting.request("POST", path, options);
  }
}
