/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.3.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class CompaniesApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  addCompany(addCompanyRequest) {
    // verify the required parameter 'addCompanyRequest' is set
    if (addCompanyRequest === undefined || addCompanyRequest === null) {
      throw new Error(
        "Missing the required parameter 'addCompanyRequest' when calling addCompany",
      );
    }

    let path = "/companies";

    let options = {
      params: {},
      data: addCompanyRequest,
    };

    return this.accounting.request("POST", path, options);
  }

  deleteCompany(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling deleteCompany",
      );
    }

    let path = "/companies/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("DELETE", path, options);
  }

  getCompany(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling getCompany",
      );
    }

    let path = "/companies/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  getCompanyCustomization(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling getCompanyCustomization",
      );
    }

    let path = "/companies/{uuid}/customization";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  getCompanyFeatureSet(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling getCompanyFeatureSet",
      );
    }

    let path = "/companies/{uuid}/features";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listCompanies(fields = null, page = null, perPage = null) {
    let path = "/companies";

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  updateCompany(uuid, addCompanyRequest) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling updateCompany",
      );
    }

    // verify the required parameter 'addCompanyRequest' is set
    if (addCompanyRequest === undefined || addCompanyRequest === null) {
      throw new Error(
        "Missing the required parameter 'addCompanyRequest' when calling updateCompany",
      );
    }

    let path = "/companies/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: addCompanyRequest,
    };

    return this.accounting.request("PUT", path, options);
  }
}
