/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.0.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class ContactsApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  addContact(addContactRequest) {
    // verify the required parameter 'addContactRequest' is set
    if (addContactRequest === undefined || addContactRequest === null) {
      throw new Error(
        "Missing the required parameter 'addContactRequest' when calling addContact",
      );
    }

    let path = "/contacts";

    let options = {
      params: {},
      data: addContactRequest,
    };

    return this.accounting.request("POST", path, options);
  }

  deleteContact(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling deleteContact",
      );
    }

    let path = "/contacts/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("DELETE", path, options);
  }

  getContact(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling getContact",
      );
    }

    let path = "/contacts/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listContactBills(uuid = null, fields = null, page = null, perPage = null) {
    let path = "/contacts/{uuid}/bills";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listContactInvoices(uuid, fields = null, page = null, perPage = null) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling listContactInvoices",
      );
    }

    let path = "/contacts/{uuid}/invoices";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listContacts(fields = null, page = null, perPage = null) {
    let path = "/contacts";

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  updateContact(uuid, addContactRequest) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling updateContact",
      );
    }

    // verify the required parameter 'addContactRequest' is set
    if (addContactRequest === undefined || addContactRequest === null) {
      throw new Error(
        "Missing the required parameter 'addContactRequest' when calling updateContact",
      );
    }

    let path = "/contacts/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: addContactRequest,
    };

    return this.accounting.request("PUT", path, options);
  }
}
