/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.3.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class CountriesApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  getTranslatedCountries(lang) {
    // verify the required parameter 'lang' is set
    if (lang === undefined || lang === null) {
      throw new Error(
        "Missing the required parameter 'lang' when calling getTranslatedCountries",
      );
    }

    let path = "/countries/{lang}";
    path = path.replace("{lang}", lang);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }
}
