/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.0.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class CredentialsApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  addCredential(addCredentialRequest) {
    // verify the required parameter 'addCredentialRequest' is set
    if (addCredentialRequest === undefined || addCredentialRequest === null) {
      throw new Error(
        "Missing the required parameter 'addCredentialRequest' when calling addCredential",
      );
    }

    let path = "/credentials";

    let options = {
      params: {},
      data: addCredentialRequest,
    };

    return this.accounting.request("POST", path, options);
  }

  deleteCredential(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling deleteCredential",
      );
    }

    let path = "/credentials/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("DELETE", path, options);
  }

  getCredential(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling getCredential",
      );
    }

    let path = "/credentials/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listCredentials(fields = null, page = null, perPage = null) {
    let path = "/credentials";

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listPermissions() {
    let path = "/credentials/permissions";

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  me() {
    let path = "/me";

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  updateCredential(uuid, addCredentialRequest) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling updateCredential",
      );
    }

    // verify the required parameter 'addCredentialRequest' is set
    if (addCredentialRequest === undefined || addCredentialRequest === null) {
      throw new Error(
        "Missing the required parameter 'addCredentialRequest' when calling updateCredential",
      );
    }

    let path = "/credentials/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: addCredentialRequest,
    };

    return this.accounting.request("PUT", path, options);
  }

  userveria() {
    let path = "/userveria";

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("POST", path, options);
  }
}
