/**
 * Accounting API
 *
 * The version of the OpenAPI document: VERSION_HERE
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class CurrencyApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  getExchangeRate(from, to) {
    // verify the required parameter 'from' is set
    if (from === undefined || from === null) {
      throw new Error(
        "Missing the required parameter 'from' when calling getExchangeRate",
      );
    }

    // verify the required parameter 'to' is set
    if (to === undefined || to === null) {
      throw new Error(
        "Missing the required parameter 'to' when calling getExchangeRate",
      );
    }

    let path = "/currency/{from}/{to}";
    path = path.replace("{from}", from);
    path = path.replace("{to}", to);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }
}
