/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class ExportApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  listExports(fields = null, page = null, perPage = null) {
    let path = "/export";

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  requestExport(requestExportRequest) {
    // verify the required parameter 'requestExportRequest' is set
    if (requestExportRequest === undefined || requestExportRequest === null) {
      throw new Error(
        "Missing the required parameter 'requestExportRequest' when calling requestExport",
      );
    }

    let path = "/export";

    let options = {
      params: {},
      data: requestExportRequest,
    };

    return this.accounting.request("POST", path, options);
  }
}
