/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.0.24
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class LogsApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  logs(
    fields = null,
    page = null,
    perPage = null,
    channel = null,
    level = null,
    resource = null,
    before = null,
    after = null,
    format = null,
  ) {
    let path = "/logs";

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
        channel: channel,
        level: level,
        resource: resource,
        before: before,
        after: after,
        format: format,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }
}
