/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class RevenuesApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  addRevenue(addRevenueRequest) {
    // verify the required parameter 'addRevenueRequest' is set
    if (addRevenueRequest === undefined || addRevenueRequest === null) {
      throw new Error(
        "Missing the required parameter 'addRevenueRequest' when calling addRevenue",
      );
    }

    let path = "/incomes/revenues";

    let options = {
      params: {},
      data: addRevenueRequest,
    };

    return this.accounting.request("POST", path, options);
  }

  deleteRevenue(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling deleteRevenue",
      );
    }

    let path = "/incomes/revenues/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("DELETE", path, options);
  }

  getRevenue(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling getRevenue",
      );
    }

    let path = "/incomes/revenues/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listRevenues(fields = null, page = null, perPage = null) {
    let path = "/incomes/revenues";

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  updateRevenue(uuid, addRevenueRequest) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling updateRevenue",
      );
    }

    // verify the required parameter 'addRevenueRequest' is set
    if (addRevenueRequest === undefined || addRevenueRequest === null) {
      throw new Error(
        "Missing the required parameter 'addRevenueRequest' when calling updateRevenue",
      );
    }

    let path = "/incomes/revenues/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: addRevenueRequest,
    };

    return this.accounting.request("PUT", path, options);
  }
}
