/**
 * Accounting API
 *
 * The version of the OpenAPI document: VERSION_HERE
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class RossumApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  listReviews(fields = null, page = null, perPage = null) {
    let path = "/external/rossum/reviews";

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }
}
