/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.3.8
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class StatisticsApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  summaryStatisticsPeriod(start = null, end = null) {
    let path = "/companies/{uuid}/statistics/summary";

    let options = {
      params: {
        start: start,
        end: end,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }
}
