/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.3.12
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class StatisticsApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  summaryStatisticsPeriod(uuid, start = null, end = null) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling summaryStatisticsPeriod",
      );
    }

    let path = "/companies/{uuid}/statistics/summary";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {
        start: start,
        end: end,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }
}
