/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.3.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class TagsApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  addTag(addTagRequest) {
    // verify the required parameter 'addTagRequest' is set
    if (addTagRequest === undefined || addTagRequest === null) {
      throw new Error(
        "Missing the required parameter 'addTagRequest' when calling addTag",
      );
    }

    let path = "/tags";

    let options = {
      params: {},
      data: addTagRequest,
    };

    return this.accounting.request("POST", path, options);
  }

  deleteTag(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling deleteTag",
      );
    }

    let path = "/tags/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("DELETE", path, options);
  }

  getTag(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling getTag",
      );
    }

    let path = "/tags/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listTags(fields = null, page = null, perPage = null) {
    let path = "/tags";

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listTagsByResource(resource, fields = null, page = null, perPage = null) {
    // verify the required parameter 'resource' is set
    if (resource === undefined || resource === null) {
      throw new Error(
        "Missing the required parameter 'resource' when calling listTagsByResource",
      );
    }

    let path = "/tags/attachments/{resource}";
    path = path.replace("{resource}", resource);

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  updateTag(uuid, addTagRequest) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling updateTag",
      );
    }

    // verify the required parameter 'addTagRequest' is set
    if (addTagRequest === undefined || addTagRequest === null) {
      throw new Error(
        "Missing the required parameter 'addTagRequest' when calling updateTag",
      );
    }

    let path = "/tags/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: addTagRequest,
    };

    return this.accounting.request("PUT", path, options);
  }
}
