/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.3.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class TaxApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  getTaxRate(country) {
    // verify the required parameter 'country' is set
    if (country === undefined || country === null) {
      throw new Error(
        "Missing the required parameter 'country' when calling getTaxRate",
      );
    }

    let path = "/tax/{country}";
    path = path.replace("{country}", country);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  verifyVatId(number) {
    // verify the required parameter 'number' is set
    if (number === undefined || number === null) {
      throw new Error(
        "Missing the required parameter 'number' when calling verifyVatId",
      );
    }

    let path = "/vat/verify/{number}";
    path = path.replace("{number}", number);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }
}
