/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.0.24
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class TransfersApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  addTransfer(addTransferRequest) {
    // verify the required parameter 'addTransferRequest' is set
    if (addTransferRequest === undefined || addTransferRequest === null) {
      throw new Error(
        "Missing the required parameter 'addTransferRequest' when calling addTransfer",
      );
    }

    let path = "/transfers";

    let options = {
      params: {},
      data: addTransferRequest,
    };

    return this.accounting.request("POST", path, options);
  }

  deleteTransfer(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling deleteTransfer",
      );
    }

    let path = "/transfers/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("DELETE", path, options);
  }

  getTransfer(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling getTransfer",
      );
    }

    let path = "/transfers/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listTransfers(fields = null, page = null, perPage = null) {
    let path = "/transfers";

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  updateTransfer(uuid, addTransferRequest) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling updateTransfer",
      );
    }

    // verify the required parameter 'addTransferRequest' is set
    if (addTransferRequest === undefined || addTransferRequest === null) {
      throw new Error(
        "Missing the required parameter 'addTransferRequest' when calling updateTransfer",
      );
    }

    let path = "/transfers/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: addTransferRequest,
    };

    return this.accounting.request("PUT", path, options);
  }
}
