/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class UsersApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  addUser(addUserRequest) {
    // verify the required parameter 'addUserRequest' is set
    if (addUserRequest === undefined || addUserRequest === null) {
      throw new Error(
        "Missing the required parameter 'addUserRequest' when calling addUser",
      );
    }

    let path = "/users";

    let options = {
      params: {},
      data: addUserRequest,
    };

    return this.accounting.request("POST", path, options);
  }

  deleteUser(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling deleteUser",
      );
    }

    let path = "/users/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("DELETE", path, options);
  }

  getUser(uuid) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling getUser",
      );
    }

    let path = "/users/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listUsers(fields = null, page = null, perPage = null) {
    let path = "/users";

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  updateUser(uuid, updateUserRequest) {
    // verify the required parameter 'uuid' is set
    if (uuid === undefined || uuid === null) {
      throw new Error(
        "Missing the required parameter 'uuid' when calling updateUser",
      );
    }

    // verify the required parameter 'updateUserRequest' is set
    if (updateUserRequest === undefined || updateUserRequest === null) {
      throw new Error(
        "Missing the required parameter 'updateUserRequest' when calling updateUser",
      );
    }

    let path = "/users/{uuid}";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: updateUserRequest,
    };

    return this.accounting.request("PUT", path, options);
  }

  usersCompanies() {
    let path = "/users/me/companies";

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  usersMe() {
    let path = "/users/me";

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }
}
