/**
 * Accounting API
 *
 * The version of the OpenAPI document: 7.5.8
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

export class VATIDApi {
  accounting;

  constructor(accounting) {
    this.accounting = accounting;
  }

  addCompanyVatId(addCompanyVatIdRequest, uuid = null) {
    // verify the required parameter 'addCompanyVatIdRequest' is set
    if (
      addCompanyVatIdRequest === undefined ||
      addCompanyVatIdRequest === null
    ) {
      throw new Error(
        "Missing the required parameter 'addCompanyVatIdRequest' when calling addCompanyVatId",
      );
    }

    let path = "/companies/{uuid}/vat";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {},
      data: addCompanyVatIdRequest,
    };

    return this.accounting.request("POST", path, options);
  }

  deleteCompanyVatId(key, uuid = null) {
    // verify the required parameter 'key' is set
    if (key === undefined || key === null) {
      throw new Error(
        "Missing the required parameter 'key' when calling deleteCompanyVatId",
      );
    }

    let path = "/companies/{uuid}/vat/{key}";
    path = path.replace("{uuid}", uuid);
    path = path.replace("{key}", key);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("DELETE", path, options);
  }

  getCompanyVatId(key, uuid = null) {
    // verify the required parameter 'key' is set
    if (key === undefined || key === null) {
      throw new Error(
        "Missing the required parameter 'key' when calling getCompanyVatId",
      );
    }

    let path = "/companies/{uuid}/vat/{key}";
    path = path.replace("{uuid}", uuid);
    path = path.replace("{key}", key);

    let options = {
      params: {},
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  listCompanyVatId(fields = null, page = null, perPage = null, uuid = null) {
    let path = "/companies/{uuid}/vat";
    path = path.replace("{uuid}", uuid);

    let options = {
      params: {
        fields: fields,
        page: page,
        per_page: perPage,
      },
      data: {},
    };

    return this.accounting.request("GET", path, options);
  }

  updateCompanyVatId(key, addCompanyVatIdRequest, uuid = null) {
    // verify the required parameter 'key' is set
    if (key === undefined || key === null) {
      throw new Error(
        "Missing the required parameter 'key' when calling updateCompanyVatId",
      );
    }

    // verify the required parameter 'addCompanyVatIdRequest' is set
    if (
      addCompanyVatIdRequest === undefined ||
      addCompanyVatIdRequest === null
    ) {
      throw new Error(
        "Missing the required parameter 'addCompanyVatIdRequest' when calling updateCompanyVatId",
      );
    }

    let path = "/companies/{uuid}/vat/{key}";
    path = path.replace("{uuid}", uuid);
    path = path.replace("{key}", key);

    let options = {
      params: {},
      data: addCompanyVatIdRequest,
    };

    return this.accounting.request("PUT", path, options);
  }
}
