/**
 * Accounting API
 *
 * The version of the OpenAPI document: VERSION_HERE
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import MockAdapter from "axios-mock-adapter";
import axios from "axios";
import { Accounting } from "../../src/index.js";

let mock = new MockAdapter(axios);

describe("CountriesApi", function () {
  describe("getTranslatedCountries", function () {
    it("should call getTranslatedCountries successfully", function (done) {
      let path = "/countries/{lang}";
      path = path.replace("{" + "lang" + "}", "lang_example");

      mock.onAny(path).reply(200, {});
      let accounting = new Accounting(
        "fake-token",
        "https://fake-endpoint.accounting.sh",
      );
      accounting.countries
        .getTranslatedCountries("lang_example")
        .then(() => {
          done();
        })
        .catch(() => {
          done(false);
        });
    });
  });
});
