/**
 * Accounting API
 *
 * The version of the OpenAPI document: VERSION_HERE
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import MockAdapter from "axios-mock-adapter";
import axios from "axios";
import { Accounting } from "../../src/index.js";

let mock = new MockAdapter(axios);

describe("SettingsApi", function () {
  describe("getSettings", function () {
    it("should call getSettings successfully", function (done) {
      let path = "/companies/{uuid}/settings/{key}";
      path = path.replace("{" + "uuid" + "}", "uuid_example");
      path = path.replace("{" + "key" + "}", "key_example");

      mock.onAny(path).reply(200, {});
      let accounting = new Accounting(
        "fake-token",
        "https://fake-endpoint.accounting.sh",
      );
      accounting.settings
        .getSettings("uuid_example", "key_example")
        .then(() => {
          done();
        })
        .catch(() => {
          done(false);
        });
    });
  });
  describe("listSettings", function () {
    it("should call listSettings successfully", function (done) {
      let path = "/companies/{uuid}/settings";
      path = path.replace("{" + "uuid" + "}", "uuid_example");

      mock.onAny(path).reply(200, {});
      let accounting = new Accounting(
        "fake-token",
        "https://fake-endpoint.accounting.sh",
      );
      accounting.settings
        .listSettings(
          "fields_example",
          "page_example",
          "perPage_example",
          "uuid_example",
        )
        .then(() => {
          done();
        })
        .catch(() => {
          done(false);
        });
    });
  });
  describe("updateSettings", function () {
    it("should call updateSettings successfully", function (done) {
      let path = "/companies/{uuid}/settings/{key}";
      path = path.replace("{" + "uuid" + "}", "uuid_example");
      path = path.replace("{" + "key" + "}", "key_example");

      mock.onAny(path).reply(200, {});
      let accounting = new Accounting(
        "fake-token",
        "https://fake-endpoint.accounting.sh",
      );
      accounting.settings
        .updateSettings("uuid_example", "key_example", {})
        .then(() => {
          done();
        })
        .catch(() => {
          done(false);
        });
    });
  });
});
