/**
 * Accounting API
 *
 * The version of the OpenAPI document: 8.3.8
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import MockAdapter from "axios-mock-adapter";
import axios from "axios";
import { Accounting } from "../../src/index.js";

let mock = new MockAdapter(axios);

describe("StatisticsApi", function () {
  describe("summaryStatisticsPeriod", function () {
    it("should call summaryStatisticsPeriod successfully", function (done) {
      let path = "/companies/{uuid}/statistics/summary";

      mock.onAny(path).reply(200, {});
      let accounting = new Accounting(
        "fake-token",
        "https://fake-endpoint.accounting.sh",
      );
      accounting.statistics
        .summaryStatisticsPeriod(new Date("2013-10-20"), new Date("2013-10-20"))
        .then(() => {
          done();
        })
        .catch(() => {
          done(false);
        });
    });
  });
});
