/**
 * Accounting API
 *
 * The version of the OpenAPI document: VERSION_HERE
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import MockAdapter from "axios-mock-adapter";
import axios from "axios";
import { Accounting } from "../../src/index.js";

let mock = new MockAdapter(axios);

describe("VATIDApi", function () {
  describe("addCompanyVatId", function () {
    it("should call addCompanyVatId successfully", function (done) {
      let path = "/companies/{uuid}/vat";
      path = path.replace("{" + "uuid" + "}", "uuid_example");

      mock.onAny(path).reply(200, {});
      let accounting = new Accounting(
        "fake-token",
        "https://fake-endpoint.accounting.sh",
      );
      accounting.vATID
        .addCompanyVatId({}, "uuid_example")
        .then(() => {
          done();
        })
        .catch(() => {
          done(false);
        });
    });
  });
  describe("deleteCompanyVatId", function () {
    it("should call deleteCompanyVatId successfully", function (done) {
      let path = "/companies/{uuid}/vat/{key}";
      path = path.replace("{" + "uuid" + "}", "uuid_example");
      path = path.replace("{" + "key" + "}", "key_example");

      mock.onAny(path).reply(200, {});
      let accounting = new Accounting(
        "fake-token",
        "https://fake-endpoint.accounting.sh",
      );
      accounting.vATID
        .deleteCompanyVatId("key_example", "uuid_example")
        .then(() => {
          done();
        })
        .catch(() => {
          done(false);
        });
    });
  });
  describe("getCompanyVatId", function () {
    it("should call getCompanyVatId successfully", function (done) {
      let path = "/companies/{uuid}/vat/{key}";
      path = path.replace("{" + "uuid" + "}", "uuid_example");
      path = path.replace("{" + "key" + "}", "key_example");

      mock.onAny(path).reply(200, {});
      let accounting = new Accounting(
        "fake-token",
        "https://fake-endpoint.accounting.sh",
      );
      accounting.vATID
        .getCompanyVatId("key_example", "uuid_example")
        .then(() => {
          done();
        })
        .catch(() => {
          done(false);
        });
    });
  });
  describe("listCompanyVatId", function () {
    it("should call listCompanyVatId successfully", function (done) {
      let path = "/companies/{uuid}/vat";
      path = path.replace("{" + "uuid" + "}", "uuid_example");

      mock.onAny(path).reply(200, {});
      let accounting = new Accounting(
        "fake-token",
        "https://fake-endpoint.accounting.sh",
      );
      accounting.vATID
        .listCompanyVatId(
          "fields_example",
          "page_example",
          "perPage_example",
          "uuid_example",
        )
        .then(() => {
          done();
        })
        .catch(() => {
          done(false);
        });
    });
  });
  describe("updateCompanyVatId", function () {
    it("should call updateCompanyVatId successfully", function (done) {
      let path = "/companies/{uuid}/vat/{key}";
      path = path.replace("{" + "uuid" + "}", "uuid_example");
      path = path.replace("{" + "key" + "}", "key_example");

      mock.onAny(path).reply(200, {});
      let accounting = new Accounting(
        "fake-token",
        "https://fake-endpoint.accounting.sh",
      );
      accounting.vATID
        .updateCompanyVatId("key_example", {}, "uuid_example")
        .then(() => {
          done();
        })
        .catch(() => {
          done(false);
        });
    });
  });
});
